apiVersion: apps/v1
kind: Deployment
metadata:
  name: vorboss 
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: vorboss
  template:
    metadata:
      labels:
        app: vorboss
    spec:
      containers:
      - name: app
        image: i0nw/vorboss:latest
        imagePullPolicy: Always
        env:
          - name: APP_ENVIRONMENT
            value: production
          - name: LOG_LEVEL
            value: debug
          - name: "AIRTABLE_API_KEY"
            valueFrom:
              secretKeyRef:
                name: airtable-api-creds
                key: private-api-key
        ports:
        - containerPort: 8000
          protocol: TCP
      imagePullSecrets:
      - name: dockerhub
